# Simplified values.yaml for Apache Airflow Helm Chart
# This configuration focuses primarily on the Git Sync feature for synchronizing DAGs.
# It includes basic settings for Airflow with CeleryExecutor, along with essential components like
# the Airflow scheduler, workers, Redis, and PostgreSQL.

# Airflow home directory
airflowHome: /opt/airflow

# Default airflow repository and tag (used for Docker images)
defaultAirflowRepository: apache/airflow
defaultAirflowTag: "2.7.1"

# Git Sync for DAGs
dags:
  gitSync:
    enabled: true
    repo: https://github.com/georgeerol/K8sHelmFlow.git
    branch: master
    rev: HEAD
    depth: 1
    maxFailures: 0
    subPath: "dags"

# Airflow Executor
executor: "CeleryExecutor"

# Scheduler configuration
scheduler:
  replicas: 1

# Airflow Worker configuration
workers:
  replicas: 1

# Redis configuration (used by CeleryExecutor)
redis:
  enabled: true

# PostgreSQL configuration (default database)
postgresql:
  enabled: true
  image:
    tag: "11"
  auth:
    enablePostgresUser: true
    postgresPassword: postgres
    username: ""
    password: ""

# Logs configuration
logs:
  persistence:
    enabled: false

# Service account configuration
serviceAccount:
  create: true

# Security contexts
securityContexts:
  pod: {}
  container: {}

# Resource management
resources: {}

# Node selection
nodeSelector: {}

# Health checks and probes
livenessProbe: {}
readinessProbe: {}
startupProbe: {}

# Environment variables
env: []

# Volume and volume mounts
volumes: []
volumeMounts: []
